
services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - "-c"
      - "standalone.xml"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"